# Generated by Django 5.0.6 on 2024-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('terrains', models.CharField(max_length=200)),
                ('climates', models.CharField(max_length=200)),
            ],
        ),
    ]
